### ISSUE TITLE
Skip non-files

### ISSUE THREAD

**Issue by max-sixty** [MShekow/directory-checksum#6]
The project looks great! I was hoping to use it for debugging Docker issues.

Currently it raises an error on git's filewatcher. Would it be reasonable to skip those?

```
.git/fsmonitor--daemon.ipc: operation not supported on socket
```

**Comment by MShekow** [comment]
Thanks for reporting it. I think I will change the code so that `directory-checksum` skips files such as device files, sockets, and other weird file modes (and print a warning for the skipped files).

Meanwhile, `directory-checksum` will most likely work inside your Docker container, it just fails on your macOS/UNIX _host_ where the Git file watcher uses this kind of file.
